GITHUB_KEY: a3b18ada963f4c0b4219
GITHUB_SECRET: d02559474a06aa5a52789d6a45e9f8e38a993110
GITHUB_TOKEN:  83ace51eca8439fe9dabcdc9db2957a97163027d

TWITTER_ACCESS_TOKEN:
TWITTER_ACCESS_TOKEN_SECRET:
TWITTER_KEY:
TWITTER_SECRET:

ALGOLIASEARCH_API_KEY:
ALGOLIASEARCH_APPLICATION_ID:
ALGOLIASEARCH_SEARCH_ONLY_KEY:

PUSHER_APP_ID:
PUSHER_KEY:
PUSHER_SECRET:
PUSHER_CLUSTER:

DATABASE_URL: postgres://postgres:123456@localhost:5432
PRACTICALDEVELOPER_DATABASE_PASSWORD: 123456